### ISSUE TITLE
Increase the accuracy Distance estimation

### ISSUE THREAD

**Issue by Asadullah-Dal17** [Asadullah-Dal17/Distance_measurement_using_single_camera#1]
Is there any way to increase the accuracy of distance estimation..

**Comment by AB-Kafi** [comment]
i don't think there is any other way. because there is no real reference point. you need a reference point for that.

**Comment by Asadullah-Dal17** [comment]
If  calibrate the camera, we can generate z coordinate. 
Can we consider that as depth?

**Comment by slesafir** [comment]
Can the height of the camera be a reference point? Especially if it is on the ground?

**Comment by Asadullah-Dal17** [comment]
The reference point, here is you must have the information of the object in the real world, like the height and distance apart from the camera. the placement of the camera does not affect much here.
