### ISSUE TITLE
About the return values of  face_detector.detectMultiScale

### ISSUE THREAD

**Issue by Lai-YT** [Asadullah-Dal17/Distance_measurement_using_single_camera#19]
I took a glance on your **Updated_distance.py** file, and I had a little problem on [line 93](https://github.com/Asadullah-Dal17/Distance_measurement_using_single_camera/blob/b84442f69857b9135f6421c8803c9fb35d10b408/Updated_distance.py#L93).
Should the values in `faces` be `(x, y, w, h)` instead of `(x, y, h, w)`?
Also thanks to your project!
I'm currently working on single-camera applications, the efforts you paid helps me a lot!

**Comment by Asadullah-Dal17** [comment]
Thank you so much for your response ❤️, I have addressed the issue, 
Note: It won't affect the distance estimation accuracy, since the detected face is square.
